# build stage
FROM node:alpine AS build-stage

WORKDIR /app
# Copy package.json and package-lock.json/yarn.lock from the 'frontend' directory
# The source path 'frontend/package.json' is relative to the build context (project root)
COPY frontend/package*.json ./

RUN npm install

COPY frontend/. .

EXPOSE 3000

CMD ["npm", "run", "dev"]

