services:
  #Nginx Web Server Service
  webserver:
    image: nginx:stable-alpine
    container_name: joomart-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80" # HTTP port for redirection
      - "443:443" # HTTPS port
    volumes:
      # Mount the Nginx configuration.
      - ../../config/nginx:/etc/nginx/conf.d
      # Mount the SSL certificates.
      - ../../config/nginx/certs:/etc/nginx/certs
      # Mount the Vue app's production build from its build context.
      # The path is now relative to the location of this compose file.
      - ../../frontend/dist:/usr/share/nginx/html
      # You can still mount the api public directory if you need it.
      - ../../api/public:/var/www/html/public
    depends_on:
      # Use `service_healthy` to prevent Nginx from starting until dependencies are ready.
      api:
        condition: service_healthy
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    networks:
      - joomart-network

  #Laravel API Service
  api:
    build:
      context: ../../
      dockerfile: dockerfiles/Dockerfile.api.prod
    image: ghcr.io/lexluga/joomart-api:latest
    container_name: joomart-api
    working_dir: /var/www/html
    volumes:
      - ../../api:/var/www/html
    env_file:
      - ../../api:/.env
    environment:
      REDIS_HOST: redis
      SERVICE_NAME: joomart-api
      SERVICE_TAGS: staging
    restart: unless-stopped
    tty: true
    expose:
      - "9000"
    depends_on:
      - db
      - redis
    networks:
      - joomart-network
      # Add a health check to ensure the service is ready before Nginx routes traffic.
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  #Vue Frontend Service
  frontend:
    build:
      context: ../../
      dockerfile: dockerfiles/Dockerfile.frontend.prod
    image: joomart-frontend
    container_name: joomart-vue-app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ../../frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      VUE_APP_FRONTEND_URL: http://staging.joomart.xyz
      VUE_APP_API_URL: https://api.staging.joomart.xyz
      NODE_ENV: staging
      CHOKIDAR_USEPOLLING: true
      tty: true
      SERVICE_NAME: frontend
      SERVICE_TAGS: staging
    expose:
      - "3000"
    networks:
      - joomart-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  #NextJS Backend Service
  backend:
    build:
      context: ../../
      dockerfile: dockerfiles/Dockerfile.backend.dev
    image: joomart-backend
    container_name: joomart-nextjs-app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ../../backend:/app
      - backend_node_modules:/app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: https://admin.staging.joomart.xyz
      NEXT_PUBLIC_FRONTEND_URL:
        https://staging.joomart.xyz
        # Ensure your Next.js dev server expects the protocol as HTTPS if it's strictly enforced by Nginx
      NODE_ENV: production
      SERVICE_NAME: backend
      SERVICE_TAGS: staging
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    tty: true

    expose:
      - "5000"
    networks:
      - joomart-network

  #Database Service
  db:
    image: mysql:latest
    container_name: joomart-db
    restart: unless-stopped
    expose:
      - "3306"
    volumes:
      - ../../config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro # Read-only mount for MySQL config
      - joomart_mysql_data:/var/lib/mysql
    env_file:
      - ../../config/mysql/.env.db
    environment:
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    networks:
      - joomart-network

  #Redis Cache Service
  redis:
    image: redis:alpine
    container_name: joomart-redis-cache
    expose:
      - "6379"
    networks:
      - joomart-network

volumes:
  joomart_mysql_data:
  frontend_node_modules:
  backend_node_modules:

networks:
  joomart-network:
    driver: bridge
