services:
  #Nginx Web Server Service
  webserver:
    image: nginx:stable-alpine
    container_name: joomart-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80" # HTTP port for redirection
      - "443:443" # HTTPS port
    volumes:
      # Mount the Nginx configuration.
      - ../../config/nginx/staging:/etc/nginx/conf.d:ro
        # Mount the volume for Certbot to write its files to.
      - certbot-web:/var/www/certbot
      # Mount the volume to persist Certbot's certificate data.
      - certbot-etc:/etc/letsencrypt
      # Mount the built frontend files to serve them via Nginx.
      - ../../frontend/dist:/usr/share/nginx/html
      # You can still mount the api public directory if you need it.
      - ../../api/public:/var/www/html/public
    depends_on:
      # Use `service_healthy` to prevent Nginx from starting until dependencies are ready.
      api:
        condition: service_healthy
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    networks:
      - joomart-network

  # Certbot Service for SSL Certificates
  certbot:
    image: certbot/certbot:latest
    container_name: joomart_certbot
    volumes:
      # Mount the Certbot webroot volume to handle the domain validation.
      - certbot-web:/var/www/certbot
      # Mount the Certbot data volume to persist certificates.
      - certbot-etc:/etc/letsencrypt
    command: certonly --webroot -w /var/www/certbot --force-renewal --agree-tos --email lexvillia@gmail.com -d staging.joomart.xyz -d api.staging.joomart.xyz -d admin.staging.joomart.xyz
    # Uncomment the following line for a dry-run test without making real changes.
    # command: certonly --webroot -w /var/www/certbot --staging --agree-tos --email your-email@example.com -d staging.joomart.xyz -d api.staging.joomart.xyz -d admin.staging.joomart.xyz
    # The container will exit after it has run the command.
    # The Nginx container will still be running.
    # We use `depends_on` to ensure Nginx is up before Certbot runs.
    depends_on:
      - webserver
    networks:
      - joomart-network
    restart: unless-stopped

  #Laravel API Service
  api:
    # Use the 'build' directive to tell Docker Compose to use your local Dockerfile
    image: ghcr.io/lexluga/joomart-api:latest
    container_name: joomart-api
    working_dir: /var/www/html
    volumes:
      - ../../api/.env:/var/www/html/.env
    environment:
      REDIS_HOST: redis
      SERVICE_NAME: joomart-api
      SERVICE_TAGS: staging
    restart: unless-stopped
    tty: true
    expose:
      - "9000"
    depends_on:
      - db
      - redis
    networks:
      - joomart-network
    # Add a health check to ensure the service is ready before Nginx routes traffic.
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  #Vue Frontend Service
  frontend:
    image: ghcr.io/lexluga/joomart-frontend:latest
    container_name: joomart-vue-app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ../../frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      VUE_APP_FRONTEND_URL: http://staging.joomart.xyz
      VUE_APP_API_URL: https://api.staging.joomart.xyz
      NODE_ENV: staging
      CHOKIDAR_USEPOLLING: true
      tty: true
      SERVICE_NAME: frontend
      SERVICE_TAGS: staging
    expose:
      - "3000"
    networks:
      - joomart-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  #NextJS Backend Service
  backend:
    image: ghcr.io/lexluga/joomart-backend:latest
    container_name: joomart-nextjs-app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ../../backend:/app
      - backend_node_modules:/app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: https://admin.staging.joomart.xyz
      NEXT_PUBLIC_FRONTEND_URL:
        https://staging.joomart.xyz
        # Ensure your Next.js dev server expects the protocol as HTTPS if it's strictly enforced by Nginx
      NODE_ENV: production
      SERVICE_NAME: backend
      SERVICE_TAGS: staging
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    tty: true

    expose:
      - "5000"
    networks:
      - joomart-network

  #Database Service
  db:
    image: mysql:latest
    container_name: joomart-db
    restart: unless-stopped
    expose:
      - "3306"
    volumes:
      - ../../config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro # Read-only mount for MySQL config
      - joomart_mysql_data:/var/lib/mysql
    env_file:
      - ../../config/mysql/.env.db
    environment:
      SERVICE_NAME: mysql
      SERVICE_TAGS: staging
    networks:
      - joomart-network

  #Redis Cache Service
  redis:
    image: redis:alpine
    container_name: joomart-redis-cache
    expose:
      - "6379"
    networks:
      - joomart-network

volumes:
  joomart_mysql_data:
  frontend_node_modules:
  backend_node_modules:
  certbot-web:
  certbot-etc:

networks:
  joomart-network:
    driver: bridge
